create_clock -period 100000.000 -name clk [get_ports clk]

#switch
set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN R4 [get_ports clr]
set_property PACKAGE_PIN T4 [get_ports en]

set_property PULLUP true [get_ports clr]
set_property PULLUP true [get_ports en]
#button
set_property PACKAGE_PIN R1 [get_ports qd]

#enout

#7-led

#ring

set_property IOSTANDARD LVCMOS18 [get_ports {d[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {d[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {enout[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {enout[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {enout[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {enout[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {enout[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {enout[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {hourset[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {hourset[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {hourset[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {hourset[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {hourset[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {hourset[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {hourset[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {hourset[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ledout1[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ledout1[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ledout1[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ledout1[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ledout1[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ledout1[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ledout1[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {minuteset[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {minuteset[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {minuteset[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {minuteset[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {minuteset[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {minuteset[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {minuteset[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {minuteset[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clr]
set_property IOSTANDARD LVCMOS18 [get_ports en]
set_property IOSTANDARD LVCMOS18 [get_ports qd]
set_property IOSTANDARD LVCMOS18 [get_ports ring]
set_property PACKAGE_PIN AB2 [get_ports ring]
set_property PACKAGE_PIN V4 [get_ports {ledout1[6]}]
set_property PACKAGE_PIN W4 [get_ports {ledout1[5]}]
set_property PACKAGE_PIN T5 [get_ports {ledout1[4]}]
set_property PACKAGE_PIN U5 [get_ports {ledout1[3]}]
set_property PACKAGE_PIN W6 [get_ports {ledout1[2]}]
set_property PACKAGE_PIN W5 [get_ports {ledout1[1]}]
set_property PACKAGE_PIN U6 [get_ports {ledout1[0]}]
set_property PACKAGE_PIN V5 [get_ports {d[1]}]
set_property PACKAGE_PIN R6 [get_ports {d[0]}]
set_property PACKAGE_PIN Y3 [get_ports {enout[5]}]
set_property PACKAGE_PIN AA3 [get_ports {enout[4]}]
set_property PACKAGE_PIN AA5 [get_ports {enout[3]}]
set_property PACKAGE_PIN AB5 [get_ports {enout[2]}]
set_property PACKAGE_PIN Y4 [get_ports {enout[1]}]
set_property PACKAGE_PIN AA4 [get_ports {enout[0]}]
set_property PACKAGE_PIN V8 [get_ports {hourset[7]}]
set_property PACKAGE_PIN AA8 [get_ports {hourset[6]}]
set_property PACKAGE_PIN AB8 [get_ports {hourset[5]}]
set_property PACKAGE_PIN Y8 [get_ports {hourset[4]}]
set_property PACKAGE_PIN Y7 [get_ports {hourset[3]}]
set_property PACKAGE_PIN W9 [get_ports {hourset[2]}]
set_property PACKAGE_PIN Y9 [get_ports {hourset[1]}]
set_property PACKAGE_PIN U7 [get_ports {hourset[0]}]
set_property PACKAGE_PIN T6 [get_ports {minuteset[7]}]
set_property PACKAGE_PIN Y6 [get_ports {minuteset[6]}]
set_property PACKAGE_PIN AA6 [get_ports {minuteset[5]}]
set_property PACKAGE_PIN V7 [get_ports {minuteset[4]}]
set_property PACKAGE_PIN W7 [get_ports {minuteset[3]}]
set_property PACKAGE_PIN AB7 [get_ports {minuteset[2]}]
set_property PACKAGE_PIN AB6 [get_ports {minuteset[1]}]
set_property PACKAGE_PIN V9 [get_ports {minuteset[0]}]
